export class Matricula {
    constructor(
        public idmatricula: number,
        public fecha_matricula : Date,
        public nombre_alumno : string, 
        public fecha_nacimiento : Date, 
        public lugar_nacimiento : string, 
        public edad :number, 
        public identidad : string,
        public tipo_sangre : string, 
        public alergias : string, 
        public enfermedades : string, 
        public vacunas : string, 
        public otros : string,
        public operaciones : string, 
        public fracturas : string, 
        public dif_conducta : string, 
        public grado : string, 
        public tipo_ingreso : string, 
        public repitente : string, 
        public escuela_ant : string, 
        public nombre_padre : string, 
        public padre_id : string, 
        public padre_edad : number,
        public padre_academ : string, 
        public padre_trabajo : string,
        public padre_trabajo_tel: string, 
        public padre_tel: string, 
        public nombre_madre: string, 
        public madre_id : string,
        public madre_edad : number, 
        public madre_academ: string,
        public madre_trabajo: string, 
        public madre_trabajo_tel: string,
        public madre_tel: string, 
        public responsable: string,
        public direccion_resp: string,
        public tel_resp: string,
        public familiar: string, 
        public tel_familiar: string, 
        public amigo: string, 
        public tel_amigo: string, 
        public vecino: string, 
        public tel_vecino: string
    
    ) {

    }
}